inherit_from: .rubocop_todo.yml
inherit_mode:
  merge:
    - Exclude

require:
  - ./lib/rubocop/cop/tinyagent/description_wording.rb

plugins:
  - rubocop-rake
  - rubocop-rbs_inline
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - ".ruby-lsp/**/*"
    - "db/**/*"

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - Steepfile

Style/OneClassPerFile:
  Exclude:
    - "script/**/*"

Layout/LineLength:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
  AllowSteepAnnotation: true

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Max: 7
  CountAsOne: ["array", "heredoc", "method_call"]
  Exclude:
    - "spec/e2e/**/*"
    - "spec/support/**/*"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/e2e/**/*"
    - "spec/support/**/*"

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/SpecFilePathFormat:
  CustomTransform:
    OpenAI: openai

RSpec/DescribeClass:
  Exclude:
    - "spec/e2e/**/*"

Style/CommentedKeyword:
  Enabled: false # because of RBS annotations

Style/Documentation:
  AllowedConstants:
    - ClassMethods
    - PrependFeatures

Style/EmptyClassDefinition:
  AllowedParentClasses:
    - Sequel::Model

Style/RedundantBegin:
  Enabled: false # because of Steep annotations

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: true

Style/RbsInline/MissingTypeAnnotation:
  EnforcedStyle: doc_style_and_return_annotation
  Exclude:
    - "script/**/*"
    - "spec/**/*"

Style/RbsInline/RequireRbsInlineComment:
  EnforcedStyle: never

Style/RbsInline/UntypedInstanceVariable:
  Exclude:
    - "script/**/*"
    - "spec/**/*"

TinyAgent/DescriptionWording:
  Enabled: true
  DisallowedPatterns: ["basic"]
