# frozen_string_literal: true

require 'spec_helper'
require 'tmpdir'
require 'pathname'

require_relative '../../script/generate-schema-model-rbs'

RSpec.describe SchemaModelRbsGenerator do
  let(:output_dir) { Pathname(Dir.mktmpdir) }
  let(:output_file) { output_dir / 'schema_models.rbs' }
  let(:content) { output_file.read }

  after do
    FileUtils.rm_rf(output_dir)
  end

  before do
    described_class.new(output_path: output_dir.to_s).process
  end

  describe '#process' do
    it 'generates RBS file with all model class definitions' do
      expect(content).to include('class Message < ThreadItem')
        .and include('class ThreadItem < Model')
        .and include('class ToolCall < Model')
        .and include('class Thread < Model')
        .and include('class Session < Model')
    end

    it 'generates column accessors for Message' do
      expect(content).to include('def role_id: () -> Integer')
        .and include('def role_id=: (Integer) -> Integer')
        .and include('def content: () -> String?')
        .and include('def content=: (String?) -> String?')
        .and include('def token_usage_prompt_tokens: () -> Integer?')
        .and include('def token_usage_total_tokens: () -> Integer?')
        .and include('def token_usage_token_limit: () -> Integer?')
    end

    it 'generates initialize for Message' do
      expect(content).to include('def initialize: (role_id: Integer, ?content: String?,')
        .and include('?token_usage_prompt_tokens: Integer?,')
        .and include('?token_usage_total_tokens: Integer?,')
        .and include('?token_usage_token_limit: Integer?) -> void')
    end

    it 'generates initialize for ToolCall' do
      expect(content).to include('def initialize: (api_id: String, name: String, ?message_id: Integer?,')
        .and include('?arguments: String?,')
        .and include('?response: String?) -> void')
    end

    it 'generates column accessors for ToolCall' do
      expect(content).to include('def message_id: () -> Integer?')
        .and include('def api_id: () -> String')
        .and include('def name: () -> String')
        .and include('def arguments: () -> String?')
        .and include('def response: () -> String?')
    end

    it 'generates column accessors for ThreadItem' do
      expect(content).to include('def thread_id: () -> Integer?')
        .and include('def type: () -> String')
        .and include('def created_at: () -> Time')
    end

    it 'generates column accessors for Thread' do
      expect(content).to include('def session_id: () -> Integer?')
        .and include('def session_id=: (Integer?) -> Integer?')
    end

    it 'generates column accessors for Session' do
      expect(content).to include('def thread_id: () -> Integer?')
        .and include('def thread_id=: (Integer?) -> Integer?')
    end

    it 'includes header comment' do
      expect(content).to include('Generated RBS definitions for Sequel models')
        .and include('automatically generated by script/generate-schema-model-rbs.rb')
    end
  end
end
