module Dry
  class CLI
    def initialize: (?untyped? command_or_registry) ?{ (*untyped) -> untyped } -> void

    def call: (?arguments: ::Array[::String], ?out: ::IO, ?err: ::IO) -> void
  end

  class CLI::Command
    def self.desc: (::String description) -> void
  end

  module CLI::Registry
    def register: (::String name, ?untyped? command, ?aliases: ::Array[::String], ?hidden: bool) ?{ (*untyped) -> untyped } -> void
  end
end
