# This file is generated by `rake db:schema:dump`. Do not modify this file manually.
Sequel.migration do
  change do
    create_table(:schema_migrations) do
      String :filename, size: 255, null: false
      
      primary_key [:filename]
    end
    
    create_table(:messages) do
      primary_key :id
      Integer :role_id, null: false
      String :content, text: true
      Integer :token_usage_prompt_tokens
      Integer :token_usage_completion_tokens
      Integer :token_usage_total_tokens
      Integer :token_usage_token_limit
    end
    
    create_table(:tool_calls) do
      primary_key :id
      foreign_key :message_id, :messages
      String :api_id, size: 255, null: false
      String :name, size: 255, null: false
      String :arguments, text: true
      String :response, text: true
    end
    
    create_table(:sessions) do
      primary_key :id
      Integer :thread_id
    end
    
    create_table(:threads) do
      primary_key :id
      foreign_key :session_id, :sessions
    end
    
    create_table(:thread_items) do
      primary_key :id
      foreign_key :thread_id, :threads
      String :type, size: 255, null: false
      DateTime :created_at, default: Sequel::CURRENT_TIMESTAMP, null: false
    end
    
    alter_table(:messages) do
      add_foreign_key [:id], :thread_items, key: nil
    end
    
    alter_table(:sessions) do
      add_foreign_key [:thread_id], :threads, key: nil
    end
  end
end
