#!/usr/bin/env ruby
# frozen_string_literal: true

require 'tinyagent'
require 'pathname'
require 'fileutils'

# Generate RBS type definitions for Sequel model classes from database schema.
class SchemaModelRbsGenerator
  COLUMN_TYPE_MAP = {
    integer: 'Integer',
    string: 'String',
    datetime: 'Time',
    boolean: 'bool',
    float: 'Float',
    decimal: 'Float',
    blob: 'String'
  }.freeze

  ModelInfo = Data.define(
    :klass,            #: untyped
    :name,             #: String
    :superclass_name,  #: String
    :columns           #: Array[ColumnInfo]
  )

  ColumnInfo = Data.define(
    :name,      #: String
    :rbs_type,  #: String
    :nullable   #: bool
  )

  def initialize(output_path: 'sig/generated-by-scripts')
    @output_path = Pathname(output_path)
  end

  def process
    models = collect_models
    rbs_content = generate_rbs(models)

    FileUtils.mkdir_p(@output_path)
    output_file = @output_path / 'schema_models.rbs'
    File.write(output_file, rbs_content)
    puts "Generated #{output_file}"
  end

  private

  def collect_models
    model_classes = [
      Tinyagent::ThreadItem,
      Tinyagent::Message,
      Tinyagent::ToolCall,
      Tinyagent::Thread,
      Tinyagent::Session
    ]

    model_classes.filter_map do |klass|
      columns = extract_columns(klass)
      next if columns.empty?

      superclass_name = klass.superclass == Tinyagent::ThreadItem ? 'ThreadItem' : 'Model'

      ModelInfo.new(
        klass: klass,
        name: klass.name.sub('Tinyagent::', ''),
        superclass_name: superclass_name,
        columns: columns
      )
    end
  end

  def extract_columns(klass)
    schema = klass.db_schema
    inherited_columns = if klass.superclass.respond_to?(:db_schema) && klass.superclass != Tinyagent::Model
                          klass.superclass.db_schema.keys
                        else
                          []
                        end

    schema.filter_map do |col_name, col_info|
      next if col_info[:primary_key]
      next if inherited_columns.include?(col_name)

      rbs_type = COLUMN_TYPE_MAP.fetch(col_info[:type], 'untyped')
      nullable = col_info[:allow_null]

      ColumnInfo.new(
        name: col_name.to_s,
        rbs_type: rbs_type,
        nullable: nullable
      )
    end
  end

  def generate_rbs(models)
    content = []
    content << '# Generated RBS definitions for Sequel models'
    content << '# This file is automatically generated by script/generate-schema-model-rbs.rb'
    content << ''
    content << 'module Tinyagent'

    models.each do |model|
      content << "  class #{model.name} < #{model.superclass_name}"

      model.columns.each do |col|
        rbs_type = col.nullable ? "#{col.rbs_type}?" : col.rbs_type
        setter_type = rbs_type

        content << "    def #{col.name}: () -> #{rbs_type}"
        content << "    def #{col.name}=: (#{setter_type}) -> #{setter_type}"
      end

      init_optional, init_required = model.columns.partition(&:nullable)
      init_parts = []
      init_required.each do |col|
        rbs_type = col.rbs_type
        init_parts << "#{col.name}: #{rbs_type}"
      end
      init_optional.each do |col|
        rbs_type = "#{col.rbs_type}?"
        init_parts << "?#{col.name}: #{rbs_type}"
      end
      content << "    def initialize: (#{init_parts.join(', ')}) -> void" unless init_parts.empty?

      content << '  end'
      content << ''
    end

    content << 'end'
    content.join("\n")
  end
end

if __FILE__ == $PROGRAM_NAME
  Tinyagent::Migrations.run
  SchemaModelRbsGenerator.new.process
end
